export const RECEIVE_ALL_GENRES = 'RECEIVE_ALL_GENRES';
export const RECEIVE_GENRE = 'RECEIVE_GENRE';

export const RECEIVE_LIST = "RECEIVE_LIST";

export const REMOVE_LIST_ITEM = "REMOVE_LIST_ITEM";
export const RECEIVE_LIST_ITEM = "RECEIVE_LIST_ITEM";

export const RECEIVE_ALL_PROFILES = 'RECEIVE_ALL_PROFILES';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
export const RECEIVE_PROFILE_ERRORS = "RECEIVE_PROFILE_ERRORS";

export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const RECEIVE_SESSIONS_ERRORS = "RECEIVE_SESSIONS_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const RECEIVE_VIDEO = "RECEIVE_VIDEO";
export const RECEIVE_ALL_VIDEOS = "RECEIVE_ALL_VIDEOS";

export const RECEIVE_RATING = "RECEIVE_RATING";